import type { Metadata } from "next";
import Header from "../components/header";
import Sidebar from "../components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="bg-gray-100">
      <div>
        <Header />
      </div>
      <div className="flex w-full">
        <div className="w-1/5">
          <Sidebar />
        </div>
        <div className="w-4/5 m-6 h-screen bg-white rounded-md shadow-md overflow-auto">
          {children}
        </div>
      </div>
    </div>
  );
}
